repos:
- repo: https://github.com/willthames/ansible-lint.git
  rev: v4.3.5
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0  # Use the ref you want to point at
  hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-yaml
    - id: check-json
    - id: check-merge-conflict

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.10
  hooks:
    - id: shellcheck
