---
# defaults file for docker
docker__version: "19.03.1"

docker__daemon_options_log_max_size: "10m"
docker__daemon_options_log_max_file: 1000

docker__daemon_default_options: |
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "{{ docker__daemon_options_log_max_size }}",
    "max-file": "{{ docker__daemon_options_log_max_file }}"
  }

docker__daemon_options: ""
docker__daemon_environment: []

docker__users: []

docker__cron_tasks:
  - job: docker system prune -af &> /dev/null
    name: "Docker clean up"
    schedule: ["0", "0", "*", "*", "0"]
