---
- block:
    # Check if container running
    # https://docs.ansible.com/ansible/2.8/modules/docker_container_info_module.html
    - name: join_etcd_cplane | Check if rancher agent container is running
      docker_container_info:
        name: rancher-agent
      register: agent_running

    - name: join_etcd_cplane | Does container exist?
      ansible.builtin.debug:
        msg: "Control plane rancher-agent {{ 'exists' if agent_running.exists else 'does not exist' }}"

    - name:  join_etcd_cpane | Adding etcd-controlplane node to the Cluster {{ cluster_name }}
      become: true
      shell: "{{ nodecommand }} --etcd --controlplane "
      when: not agent_running.exists
  when: "inventory_hostname in groups['rancher_cplane']"
