---
- block:
    - name: join_worker_node | Check if rancher agent container is running
      docker_container_info:
        name: rancher-agent
      register: agent_running

    - name: join_worker_node | Does container exist?
      ansible.builtin.debug:
        msg: "Worker rancher-agent {{ 'exists' if agent_running.exists else 'does not exist' }}"

    - name:  join_worker_node | Adding worker node to the Cluster {{ cluster_name }}
      become: true
      shell: "{{ nodecommand }} --worker"
      when: not agent_running.exists

  when: "inventory_hostname in groups['rancher_worknode']"
