---
- block:
    - name: Check Cluster and fetch clusterId
      uri:
        url: "{{ rancher_server_url }}/{{ rest_version }}/clusters?name={{ cluster_name }}"
        method: GET
        force_basic_auth: yes
        #user: "{{ userId }}"
        #password: "{{ tokenId }}"
        headers:
          Authorization: "Bearer ${{ apitoken }}"
        body_format: json
        validate_certs: no
        #return_content: yes
        #follow_redirects: yes
        status_code: 200
      register: clustercheck

    - name: Create Cluster {{ cluster_name }}
      uri:
        url: "{{ rancher_server_url }}/{{ rest_version }}/clusters"
        method: POST
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer ${{ apitoken }}"
        body: "{{ rancher__create_cluster_body }}"
        body_format: json
        validate_certs: no
        #return_content: yes
        #follow_redirects: yes
        status_code: 201
      register: clusterdata
      when: clustercheck.json['pagination']['total'] == 0

    - name: Generate clusterRegistrationToken
      uri:
        url: "{{ rancher_server_url }}/{{ rest_version }}/clusterregistrationtoken"
        method: POST
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer ${{ apitoken }}"
        body: "{\"clusterId\":\"{{ clusterdata.json['id'] }}\" }"
        body_format: json
        validate_certs: no
        #return_content: yes
        #follow_redirects: yes
        status_code: 201
      when: clustercheck.json['pagination']['total'] == 0
  when: type == "rmaster"
