---
# tasks file for docker
- name: Install yum utils
  package:
    name: yum-utils
    state: present

- name: Install device-mapper-persistent-data
  package:
    name: device-mapper-persistent-data
    state: present

- name: Install lvm2
  package:
    name: lvm2
    state: present

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Install Docker
  package:
    name: "docker-ce-{{ docker__version }}"
    state: present

- name: Create docker config folder
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Configure Docker daemon options
  template:
    src: etc/docker/daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  register: docker_json_registered
  when: docker__daemon_default_options or docker__daemon_options

- name: Generate customized environment systemd unit file
  template:
    src: etc/systemd/system/docker.service.d/environment.conf.j2
    dest: /etc/systemd/system/docker.service.d/environment.conf
    owner: root
    group: root
    mode: '0644'
  register: docker__register_systemd_customized
  when: docker__daemon_environment

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  when:
    - docker__register_systemd_customized is defined
    - docker__register_systemd_customized is changed
    - docker_json_registered is defined
    - docker_json_registered is changed

  notify: ["Restart Docker"]

- name: Add user(s) to "docker" group
  user:
    name: "{{ item }}"
    groups: "docker"
    append: true
  loop: "{{ docker__users }}"

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
